version: '3.7'

services:
  api:
    env_file:
      - ./config/staging.env
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: yarn start:dev