version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@5.0.2
jobs:
  stage:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME

workflows:
  stage_test_deploy:
    jobs:
      - stage
      - node/test:
          test-results-for: jest
          requires:
            - stage
      - deploy:
          requires:
            - node/test