version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  jest: blimmer/jest@1.0.0
jobs:
  stage:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME

workflows:
  stage_test_deploy:
    jobs:
      - stage
      - jest/test:
          package-manager: yarn
          requires:
            - stage
      - deploy:
          requires:
            - jest/test